# Generated by Django 5.2 on 2025-04-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Adresse ligne 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(max_length=3, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse de facturation',
                'verbose_name_plural': 'Adresses de facturation',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Adresse ligne 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(max_length=3, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Adresse d'expédition",
                'verbose_name_plural': "Adresses d'expédition",
            },
        ),
    ]
