# Generated by Django 5.2 on 2025-04-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la boutique')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Quartier')),
                ('shop_type', models.CharField(max_length=100, verbose_name='Type de boutique')),
                ('website', models.URLField(blank=True, verbose_name='Lien du site web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='boutiques', to='catalog.category', verbose_name='Catégories de la boutique')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
            },
        ),
    ]
